apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: external
spec:
  interval: 5m
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      version: "1.16.36"
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  targetNamespace: external
  install:
    createNamespace: true
    timeout: 15m
    remediation:
      retries: 2
  upgrade:
    timeout: 15m
    remediation:
      retries: 2
  dependsOn:
  - name: postgresql
    namespace: shared
  values:
    image:
      repository: n8nio/n8n
      tag: "2.16.0"
      pullPolicy: IfNotPresent

    # Database
    db:
      type: postgresdb

    externalPostgresql:
      host: postgresql.shared.svc.cluster.local
      port: 5432
      database: n8n
      username: n8n
      password: ""
      existingSecret: ""

    # existingEncryptionKeySecret: n8n-env

    # Main node
    main:
      count: 1
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi
      extraSecretNamesForEnvFrom:
      - n8n-env
      persistence:
        enabled: true
        size: 1Gi
        storageClass: local-path

    # Ingress
    ingress:
      enabled: true
      className: traefik
      hosts:
      - host: n8n.ngocquach.com
        paths:
        - path: /
          pathType: Prefix

    timezone: "Asia/Ho_Chi_Minh"
