# Helm Repository for Bitnami charts
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts

---
# Helm Repository for Doppler Operator
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: doppler-helm
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.doppler.com

---
# Helm Repository for Grafana
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts

---
# Helm Repository for n8n community charts
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: community-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://community-charts.github.io/helm-charts