---
# Part 1: Declare Source (SOURCE)
# Define the repository where the code is located
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-repo # Name of the source
  namespace: flux-system # Must be in this namespace
spec:
  interval: 1m # Check Git every 1 minute
  url: https://github.com/ngocxxu/infrastructure
  ref:
    branch: main # Branch to follow (usually main or master)

---
# Apps Layer - Depends on infrastructure
# Installs applications, databases, and project resources
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: infra-repo
    namespace: flux-system
  path: ./clusters/mmo-vps/apps
  dependsOn:
    - name: infrastructure
  prune: true
  wait: true
