replicaCount: 1

image:
  repository: ngocxxu/vocab-be
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Secrets configuration
secrets:
  enabled: false
  database:
    url: ""
  api:
    prefix: ""
    port: ""
    corsOrigins: ""
  swagger:
    enable: ""
  jwt:
    secret: ""
    issuer: ""
  health:
    token: ""
  passengers:
    allowed: ""
  supabase:
    url: ""
    key: ""
  redis:
    url: ""
    port: ""
    switch: ""
  email:
    user: ""
    password: ""
  frontend:
    url: ""
  fcm:
    projectId: ""
    privateKey: ""
    clientEmail: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
  hosts:
    - host: vocab-be.mooo.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - vocab-be.mooo.com

resources: 
  limits:
    memory: 120Mi
    # cpu: 200m
  requests:
    memory: 60Mi
    # cpu: 100m

# livenessProbe:
#   httpGet:
#     path: /api/v1/health
#     port: http
# readinessProbe:
#   httpGet:
#     path: /api/v1/health
#     port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
