replicaCount: 1

image:
  repository: ngocxxu/vocab-fe
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Secrets configuration
# Secret name from DopplerSecret managedSecret.name
# This secret is automatically created by Doppler Operator
secrets:
  enabled: true
  secretName: vocab-fe-env

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: vocab.ngocquach.top
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    memory: 120Mi
    cpu: 80m
  requests:
    memory: 60Mi
    cpu: 50m

# livenessProbe:
#   httpGet:
#     path: /api/v1/health
#     port: http
# readinessProbe:
#   httpGet:
#     path: /api/v1/health
#     port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
