replicaCount: 1

image:
  repository: ngocxxu/vocab-fe
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secrets:
  enabled: false
  # Backend API configuration
  nestjs:
    apiUrl: ""
  # Frontend API configuration
  nextjs:
    publicApiUrl: ""
    telemetryDisabled: ""
  # Clerk authentication
  clerk:
    secretKey: ""
    publishableKey: ""
  # PostHog analytics
  posthog:
    host: ""
  # Sentry error tracking
  sentry:
    dsn: ""
    authToken: ""
    organization: ""
    project: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
  hosts:
    - host: vocab-management.mooo.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - vocab-management.mooo.com

resources: 
  limits:
    memory: 120Mi
    # cpu: 40m
  requests:
    memory: 60Mi
    # cpu: 10m

# livenessProbe:
#   httpGet:
#     path: /api/v1/health
#     port: http
# readinessProbe:
#   httpGet:
#     path: /api/v1/health
#     port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
