{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vocab-be.fullname" . }}-secrets
  labels:
    {{- include "vocab-be.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.database }}
  {{- if .Values.secrets.database.url }}
  DATABASE_URL: {{ .Values.secrets.database.url | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.api }}
  {{- if .Values.secrets.api.prefix }}
  API_PREFIX: {{ .Values.secrets.api.prefix | b64enc }}
  {{- end }}
  {{- if .Values.secrets.api.port }}
  API_PORT: {{ .Values.secrets.api.port | b64enc }}
  {{- end }}
  {{- if .Values.secrets.api.corsOrigins }}
  API_CORS_ORIGINS: {{ .Values.secrets.api.corsOrigins | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.swagger }}
  {{- if .Values.secrets.swagger.enable }}
  SWAGGER_ENABLE: {{ .Values.secrets.swagger.enable | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.jwt }}
  {{- if .Values.secrets.jwt.secret }}
  JWT_SECRET: {{ .Values.secrets.jwt.secret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwt.issuer }}
  JWT_ISSUER: {{ .Values.secrets.jwt.issuer | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.health }}
  {{- if .Values.secrets.health.token }}
  HEALTH_TOKEN: {{ .Values.secrets.health.token | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.passengers }}
  {{- if .Values.secrets.passengers.allowed }}
  PASSENGERS_ALLOWED: {{ .Values.secrets.passengers.allowed | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.supabase }}
  {{- if .Values.secrets.supabase.url }}
  SUPABASE_URL: {{ .Values.secrets.supabase.url | b64enc }}
  {{- end }}
  {{- if .Values.secrets.supabase.key }}
  SUPABASE_KEY: {{ .Values.secrets.supabase.key | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.redis }}
  {{- if .Values.secrets.redis.url }}
  REDIS_URL: {{ .Values.secrets.redis.url | b64enc }}
  {{- end }}
  {{- if .Values.secrets.redis.port }}
  REDIS_PORT: {{ .Values.secrets.redis.port | b64enc }}
  {{- end }}
  {{- if .Values.secrets.redis.switch }}
  SWITCH_REDIS: {{ .Values.secrets.redis.switch | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.email }}
  {{- if .Values.secrets.email.user }}
  EMAIL_USER: {{ .Values.secrets.email.user | b64enc }}
  {{- end }}
  {{- if .Values.secrets.email.password }}
  EMAIL_PASSWORD: {{ .Values.secrets.email.password | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.frontend }}
  {{- if .Values.secrets.frontend.url }}
  FRONTEND_URL: {{ .Values.secrets.frontend.url | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.fcm }}
  {{- if .Values.secrets.fcm.projectId }}
  FCM_PROJECT_ID: {{ .Values.secrets.fcm.projectId | b64enc }}
  {{- end }}
  {{- if .Values.secrets.fcm.privateKey }}
  FCM_PRIVATE_KEY: {{ .Values.secrets.fcm.privateKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.fcm.clientEmail }}
  FCM_CLIENT_EMAIL: {{ .Values.secrets.fcm.clientEmail | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.external }}
  {{- range $key, $value := .Values.secrets.external }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
