apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vocab-fe
  namespace: project-vocab
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helms/vocab-fe
      sourceRef:
        kind: GitRepository
        name: infra-repo
        namespace: flux-system
  targetNamespace: project-vocab
  install:
    createNamespace: true

