apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vocab-fe
  namespace: project-vocab
spec:
  interval: 5m
  releaseName: vocab-fe
  values:
    image:
      ref: docker.io/ngocxxu/vocab-fe:0.1.44 # {"$imagepolicy": "flux-system:vocab-fe-semver"}
  chart:
    spec:
      chart: ./helms/vocab-fe
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      reconcileStrategy: Revision
  targetNamespace: project-vocab
  install:
    createNamespace: true
