replicaCount: 1

image:
  repository: diegosouzapw/omniroute
  pullPolicy: IfNotPresent
  tag: ""
  ref: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 20128
  nodePort: ""
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: omniroute.ngocquach.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: true
  existingClaim: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  annotations: {}

env:
  PORT: "20128"
  NEXT_PUBLIC_BASE_URL: "http://localhost:20128"
  NODE_ENV: "production"
  TZ: "Asia/Ho_Chi_Minh"
  ENABLE_REQUEST_LOGS: "false"

extraEnv: []

envFromSecret: ""

livenessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}

volumes: []
volumeMounts: []
