{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vocab-be.fullname" . }}-secrets
  labels:
    {{- include "vocab-be.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.database }}
  {{- if .Values.secrets.database.url }}
  DATABASE_URL: {{ .Values.secrets.database.url | b64enc }}
  {{- end }}
  {{- if .Values.secrets.database.username }}
  DATABASE_USERNAME: {{ .Values.secrets.database.username | b64enc }}
  {{- end }}
  {{- if .Values.secrets.database.password }}
  DATABASE_PASSWORD: {{ .Values.secrets.database.password | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.jwt }}
  {{- if .Values.secrets.jwt.secret }}
  JWT_SECRET: {{ .Values.secrets.jwt.secret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwt.refreshSecret }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwt.refreshSecret | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.api }}
  {{- if .Values.secrets.api.key }}
  API_KEY: {{ .Values.secrets.api.key | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.redis }}
  {{- if .Values.secrets.redis.password }}
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.email }}
  {{- if .Values.secrets.email.smtpPassword }}
  SMTP_PASSWORD: {{ .Values.secrets.email.smtpPassword | b64enc }}
  {{- end }}
  {{- if .Values.secrets.email.apiKey }}
  EMAIL_API_KEY: {{ .Values.secrets.email.apiKey | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.secrets.external }}
  {{- range $key, $value := .Values.secrets.external }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
